create table
  public.empresas (
    id_empresa serial,
    empresa character varying null,
    representante character varying null,
    cnpj character varying null,
    plano text null,
    constraint empresas_pkey primary key (id_empresa)
) tablespace pg_default;


create table
  public.colaboradores (
    id_colaborador serial,
    nome character varying null,
    setor character varying null,
    cargo character varying null,
    observacoes character varying null,
    id_empresa integer null,
    unidade text null default 'LEME'::text,
    constraint colaboradores_pkey primary key (id_colaborador)
) tablespace pg_default;

create table
  public.profissoes (
    id_profissao serial,
    profissao character varying null,
    constraint profissoes_pkey primary key (id_profissao)
) tablespace pg_default;


create table
  public.usuarios (
    id serial,
    nome character varying null,
    senha character varying null,
    ocupacao integer null,
    email character varying null,
    token character varying null,
    id_empresa integer null,
    valor real null,
    constraint usuarios_pkey primary key (id),
    constraint usuarios_token_key unique (token),
    constraint usuarios_id_empresa_fkey foreign key (id_empresa) references empresas (id_empresa),
    constraint usuarios_ocupacao_fkey foreign key (ocupacao) references profissoes (id_profissao)
) tablespace pg_default;


create table
  public.psicologo_acoes (
    id_psicologo integer not null,
    id_acoes integer not null,
    data date null,
    id_empresa integer null,
    id integer generated by default as identity,
    constraint psicologo_acoes_pkey primary key (id),
    constraint psicologo_acoes_id_psicologo_fkey foreign key (id_psicologo) references usuarios (id)
) tablespace pg_default;



create table
  public.atendimentos (
    id_atendimento serial,
    colaborador integer null,
    psicologo integer null,
    empresa integer null,
    area character varying null,
    setor character varying null,
    cidade character varying null,
    atendimento date null,
    observacoes character varying null,
    queixa_inicial character varying null,
    valor integer null,
    constraint atendimentos_pkey primary key (id_atendimento),
    constraint atendimentos_colaborador_fkey foreign key (colaborador) references colaboradores (id_colaborador),
    constraint atendimentos_empresa_fkey foreign key (empresa) references empresas (id_empresa),
    constraint atendimentos_psicologo_fkey foreign key (psicologo) references usuarios (id),
    constraint fk_atendimento_colaborador foreign key (colaborador) references colaboradores (id_colaborador),
    constraint fk_atendimento_empresa foreign key (empresa) references empresas (id_empresa)
) tablespace pg_default;


create table
  public.permissions (
    id bigint generated by default as identity,
    name character varying not null,
    created_at timestamp with time zone not null default now(),
    deleted_at timestamp without time zone null,
    constraint permissions_pkey primary key (id)
) tablespace pg_default;




create table
  public.user_permissions (
    id bigint generated by default as identity,
    user_id integer not null,
    permission_id bigint not null,
    created_at timestamp with time zone not null default now(),
    constraint user_permissions_pkey primary key (id),
    constraint user_permissions_permission_id_fkey foreign key (permission_id) references permissions (id) on delete cascade,
    constraint user_permissions_user_id_fkey foreign key (user_id) references usuarios (id) on delete cascade
) tablespace pg_default;





create table
  public.valores_empresas (
    id_empresa integer,
    valor double precision null,
    mensalidade real null,
    consultas_pagas integer null,
    coparticipativas integer null,
    constraint valores_empresas_pkey primary key (id_empresa),
    constraint valores_empresas_id_empresa_fkey foreign key (id_empresa) references empresas (id_empresa)
) tablespace pg_default;

--- No relation
create table
  public.acoes (
    id integer generated by default as identity,
    acao character varying null,
    remuneracao real null,
    constraint acoes_pkey primary key (id),
    constraint acoes_id_key unique (id)
) tablespace pg_default;


create table
  public.formularios (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text null,
    email character varying null,
    phone character varying null,
    trello_card_id character varying null,
    constraint formularios_pkey primary key (id)
) tablespace pg_default;


create table
  public.logs_login (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    email character varying null,
    nome text null,
    token character varying null,
    constraint logs_login_pkey primary key (id)
) tablespace pg_default;


create table
  public.negociacoes (
    id bigint generated by default as identity,
    empresa character varying not null,
    negociacao character varying null,
    constraint negociacoes_pkey primary key (id)
) tablespace pg_default;

